name: Deploy package
on:
  push:
    branches: [main]
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SOUNDBOKS_NPM_TOKEN: ${{ secrets.GH_PACKAGES_READ_TOKEN }}
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  HUSKY: 0
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
      issues: write
    strategy:
      matrix:
        node-version: [22.X]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx semantic-release@19
